config/routes.rb
Rails.application.routes.draw do
  resources :band_members

  root "band_members#index"
  get "about_us", to: "page#about_us", as: :about_us
  get "search_result", to: "page#search_result", as: :search_result
  get "search", to: "page#search", as: :search

end

app/models/band_member.rb
class BandMember < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/band_members_controller.rb
class BandMembersController < ApplicationController
  before_action :set_band_member, only: [:show, :edit, :update, :destroy]

  # GET /band_members
  # GET /band_members.json
  def index
    @band_members = BandMember.all;
  end

  # GET /band_members/1
  # GET /band_members/1.json
  def show
  end

  # GET /band_members/new
  def new
    @band_member = BandMember.new
  end

  # GET /band_members/1/edit
  def edit
  end

  # POST /band_members
  # POST /band_members.json
  def create
    @band_member = BandMember.new(band_member_params)

    respond_to do |format|
      if @band_member.save
        format.html { redirect_to band_members_path, notice: 'Band member was successfully created.' }
        format.json { render :show, status: :created, location: @band_member }
      else
        format.html { render :new }
        format.json { render json: @band_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /band_members/1
  # PATCH/PUT /band_members/1.json
  def update
    respond_to do |format|
      if @band_member.update(band_member_params)
        format.html { redirect_to @band_member, notice: 'Band member was successfully updated.' }
        format.json { render :show, status: :ok, location: @band_member }
      else
        format.html { render :edit }
        format.json { render json: @band_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /band_members/1
  # DELETE /band_members/1.json
  def destroy
    @band_member.destroy
    respond_to do |format|
      format.html { redirect_to band_members_url, notice: 'Band member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band_member
      @band_member = BandMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_member_params
      params.require(:band_member).permit(:name, :instrument, :looking_for, :email)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def  search_result
    @get_values = request.GET;

    #find instrument = user input in Table
    @band_members = BandMember.where( :looking_for => @get_values['looking_for']);
  end

end

# Array arr{ 'a', 'b', 'c', 'd'}, arr[3] == 'd'
# $a = 1

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/band_members_helper.rb
module BandMembersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/band_members/_form.haml
= form_for @band_member do |f|
  - if @band_member.errors.any?
    #error_explanation
      %h2= "#{pluralize(@band_member.errors.count, "error")} prohibited this band_member from being saved:"
      %ul
        - @band_member.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, placeholder: "AAA"
  .field
    = f.label :instrument
    = f.text_field :instrument
  .field
    = f.label :looking_for
    = f.text_field :looking_for
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/band_members/edit.haml
- @body_classes = "edit"

%h1 Editing band member

= render 'form'

= link_to 'Show', @band_member
\|
= link_to 'Back', root_path

app/views/band_members/index.haml
- @body_classes = "band_members"

%table
  %tr
    %th Name
    %th Instrument
    %th Looking for
    %th Email
    %th
    %th
    %th

  - @band_members.each do |band_member|
    %tr
      %td= link_to band_member.name, band_member
      %td= band_member.instrument
      %td= band_member.looking_for
      %td= band_member.email
%br

= link_to 'New Band member', new_band_member_path

app/views/band_members/new.haml
- @body_classes = "new"
%h1 New band member

= render 'form'

= link_to 'Back', root_path

app/views/band_members/show.haml
- @body_classes = "show"

%p#notice= notice

%p
  %b Name:
  = @band_member.name
%p
  %b Instrument:
  = @band_member.instrument
%p
  %b Looking for:
  = @band_member.looking_for
%p
  %b Email:
  = @band_member.email

= link_to 'Edit', edit_band_member_path(@band_member)
\|
= link_to 'Back', root_path
\|
= link_to 'Destroy', @band_member, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/layouts/_footer.haml
.footer
 %h3 It's too easy!

app/views/layouts/_title_bar.haml
.title-bar
 %h1= link_to :GarbageBand, root_path
 %p= link_to "about-us", about_us_path

app/views/layouts/application.haml
!!!5
%html
%head
  %title GarbageBand
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  = csrf_meta_tags 

%body{class: @body_classes}
  = render "layouts/title_bar"
  = yield 
  = render "layouts/footer"

app/views/page/about_us.haml
- @body_classes = "about-us"

%h1 About us
%p We are the band of garbage!

app/views/page/search.haml
%h1 search

= form_tag '/search_result', method: 'get' do
  = field_set_tag do
    = label_tag :looking_for, 'Looking For: '
    = text_field_tag :looking_for
    = submit_tag 'Search'

app/views/page/search_result.haml
%h1 search_result

%table
  %tr
    %th Name
    %th Instrument
    %th Looking for
    %th Email
    %th
    %th

  - @band_members.each do |band_member|
    %tr
      %td= link_to band_member.name, band_member
      %td= band_member.instrument
      %td= band_member.looking_for
      %td= band_member.email
  %br